#! /bin/sh

### BEGIN INIT INFO
# Provides:		ocr
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		
# Short-Description:	OCR daemon
### END INIT INFO

set -e

# /etc/init.d/ocr: start and stop the OpenBSD "secure shell(tm)" daemon
umask 022

. /lib/lsb/init-functions

# Are we running from init?
run_by_init() {
    ([ "$previous" ] && [ "$runlevel" ]) || [ "$runlevel" = S ]
}

check_for_upstart() {
    if init_is_upstart; then
	exit $1
    fi
}

check_dev_null() {
    if [ ! -c /dev/null ]; then
	if [ "$1" = log_end_msg ]; then
	    log_end_msg 1 || true
	fi
	if ! run_by_init; then
	    log_action_msg "/dev/null is not a character device!" || true
	fi
	exit 1
    fi
}

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$1" in
  start)
	log_daemon_msg "Starting OCR daemon" "ocr" || true
	if start-stop-daemon --start --quiet --oknodo --pidfile /var/run/ocr.pid --exec /usr/local/bin/ocr -- $SSHD_OPTS; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;
  stop)
	log_daemon_msg "Stopping OCR daemon" "ocr" || true
	if start-stop-daemon --stop --quiet --oknodo --pidfile /var/run/ocr.pid; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	killall ocr
	;;

  restart)
	log_daemon_msg "Restarting OCR daemon" "ocr" || true
	start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile /var/run/ocr.pid
	sleep 1
	killall ocr
	sleep 1
	if start-stop-daemon --start --quiet --oknodo --pidfile /var/run/ocr.pid --exec /usr/local/bin/ocr -- $SSHD_OPTS; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;

  try-restart)
	log_daemon_msg "Restarting OCR daemon" "ocr" || true
	RET=0
	start-stop-daemon --stop --quiet --retry 30 --pidfile /var/run/ocr.pid || RET="$?"
	sleep 1
	killall ocr
	sleep 1
	case $RET in
	    0)
		# old daemon stopped
		if start-stop-daemon --start --quiet --oknodo --pidfile /var/run/ocr.pid --exec /usr/local/bin/ocr -- $SSHD_OPTS; then
		    log_end_msg 0 || true
		else
		    log_end_msg 1 || true
		fi
		;;
	    1)
		# daemon not running
		log_progress_msg "(not running)" || true
		log_end_msg 0 || true
		;;
	    *)
		# failed to stop
		log_progress_msg "(failed to stop)" || true
		log_end_msg 1 || true
		;;
	esac
	;;

  status)
	status_of_proc -p /var/run/ocr.pid /usr/local/bin/ocr ocr && exit 0 || exit $?
	;;

  *)
	log_action_msg "Usage: /etc/init.d/ocr {start|stop|reload|force-reload|restart|try-restart|status}" || true
	exit 1
esac

exit 0
